--- #YAML:1.0
name: SQL-Abstract-Limit
version: 0.03
author:
  - David Baird <cpan@riverside-cms.co.uk>
abstract: portable LIMIT emulation
license: perl
requires:
  DBI: 0
  SQL::Abstract: 0
  Test::Exception: 0
  Test::More: 0
provides:
  SQL::Abstract::Limit:
    file: lib/SQL/Abstract/Limit.pm
    version: 0.03
generated_by: Module::Build version 0.2606
